### ISSUE TITLE
Cyclic dependencies causes maximum call-stack

### ISSUE THREAD

**Issue by pi0** [nuxt-contrib/jiti#12]
We need to preserve pending requires in a stack to resolve A -> B -> A conditions

**Comment by m0dch3n** [comment]
@pi0 I think still have this issue. The jiti version in my node_modules is 1.15.0

```javascript
[user@devserver-app-dev app (develop ✗)]$ npm i
npm ERR! code 1
npm ERR! path /home/user/workspace/app/packages/app/web
npm ERR! command failed
npm ERR! command sh -c -- nuxt prepare
npm ERR! Nuxi 3.0.0-rc.10
npm ERR! ERROR  Maximum call stack size exceeded
npm ERR! 
npm ERR!   at /home/user/workspace/app/node_modules/luxon/src/zones/systemZone.js:2:13
npm ERR!   at jiti (/home/user/workspace/app/node_modules/jiti/dist/jiti.js:1:247497)
npm ERR!   at /home/user/workspace/app/node_modules/luxon/src/settings.js:1:204
npm ERR!   at jiti (/home/user/workspace/app/node_modules/jiti/dist/jiti.js:1:247497)
npm ERR!   at /home/user/workspace/app/node_modules/luxon/src/impl/locale.js:3:40
npm ERR!   at jiti (/home/user/workspace/app/node_modules/jiti/dist/jiti.js:1:247497)
npm ERR!   at /home/user/workspace/app/node_modules/luxon/src/settings.js:3:38
npm ERR!   at jiti (/home/user/workspace/app/node_modules/jiti/dist/jiti.js:1:247497)
npm ERR!   at /home/user/workspace/app/node_modules/luxon/src/impl/locale.js:3:40
npm ERR!   at jiti (/home/user/workspace/app/node_modules/jiti/dist/jiti.js:1:247497)
```

Unfortunately a date library I'm using has these cyclic dependencies: https://github.com/moment/luxon/issues/193
