### ISSUE TITLE
can't import TS in Nuxt serverMiddleware

### ISSUE THREAD

**Issue by danielroe** [nuxt-contrib/jiti#9]
Using `jiti` with `createRequire` in Nuxt, I encountered the following issue:
```
ERROR  ServerMiddleware Error: Cannot use import statement outside a module                                0

  (function (exports, require, module, __filename, __dirname) { import qs from 'querystring'
  ^^^^^^

  SyntaxError: Cannot use import statement outside a module
  at new Script (vm.js:88:7)
  at d._moduleCompile (/my/site/node_modules/jiti/dist/jiti.js:2:25464)
  at Module.n._compile (/my/site/node_modules/jiti/dist/jiti.js:2:25015)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
  at Module.load (internal/modules/cjs/loader.js:985:32)
  at Function.Module._load (internal/modules/cjs/loader.js:878:14)
  at Module.require (internal/modules/cjs/loader.js:1025:19)
  at require (internal/modules/cjs/helpers.js:72:18)
  at Resolver.requireModule (/my/site/node_modules/@nuxt/core/dist/core.js:617:26)
  at Server._requireMiddleware (/my/site/node_modules/@nuxt/server/dist/server.js:803:39)
```

It reproduced consistently whenever using `jiti` for `createRequire` and going away whenever reverting to `esm`. It was solved by clearing `node_modules/.cache` and I have hitherto been unable to reproduce on a new install of Nuxt, even with the same/similar source files: see https://github.com/danielroe/jiti-h2-tests

**Comment by danielroe** [comment]
**EDIT**: actually that repo *does* reproduce the issue if you replace the `nuxt-ts` command with `nuxt`.

**Comment by pi0** [comment]
It is impossible that cache get's stalled since we check against checksum of file contents. With `nuxt-ts`, we disable require-engine (since esm was confliciting). I think that could be the root casue.

**Comment by danielroe** [comment]
Uninstalling `@nuxt/typescript-runtime` still triggers this bug

**Comment by pi0** [comment]
Hi @danielroe I've finally checked repro using `JITI_DEBUG` it seems `api/ts.ts` is not passing through jiti so this bug is/was from nuxt/typescript side.

Trying with 2.15 (`"nuxt-edge": "^2.15.0-26820047.b2e38f5c"`) everything works good :)
